apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: laravelsample
  name: laravelsample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravelsample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laravelsample
    spec:
      containers:
      - image: laravelsampleacr.azurecr.io/laravelsample:00d1ad70541ac32bf78a0748a1aa546f7b3190e7
        name: laravelsample
        ports:
        - containerPort: 8080
        resources: {}
